# Generated by Django 6.0.5 on 2026-05-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='img',
        ),
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
