# Generated by Django 6.0.5 on 2026-05-08 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='caps',
            options={'verbose_name': 'Cap', 'verbose_name_plural': 'Caps'},
        ),
        migrations.AddField(
            model_name='caps',
            name='color',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
