# Generated by Django 6.0.5 on 2026-05-10 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0002_alter_caps_options_caps_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='caps',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
