# Generated by Django 6.0.5 on 2026-05-10 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0003_caps_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caps',
            name='price',
            field=models.IntegerField(),
        ),
    ]
