# Generated by Django 6.0.5 on 2026-05-09 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caps', '0002_alter_caps_options_caps_color'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartsession',
            name='item',
            field=models.ManyToManyField(through='cart.CartItem', to='caps.caps'),
        ),
    ]
