# Generated by Django 6.0.5 on 2026-05-10 01:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartsession_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartsession',
            name='item',
        ),
    ]
